version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
        MYSQL_DATABASE: main
        MYSQL_USER: default
        MYSQL_ROOT_PASSWORD: root
        MYSQL_PASSWORD: root
        MYSQL_RSA_PUBLIC_KEY: ""
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

volumes:
  db-data:

networks:
  default:
    driver: bridge
